import { NowNextRail } from ".";

export default {
  title: "Components/NowNextRail",
  component: NowNextRail,
};

export const Default = {
  args: {
    leadTile: true,
    showTitle: true,
    railTitle: "Rail title",
    scrolled: true,
    focus: true,
    className: {},
    tilesClassName: {},
    tileLeadDivClassName: {},
    tileLeadRailTitleClassName: {},
    tileLeadTitle: "Title",
    visible: true,
    tilesNowNextTileTvMetaDataNowTitle: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowProviderLogo: "https://c.animaapp.com/pLg7BaBQ/img/provider-logo-104@2x.png",
    tilesNowNextTileTvMetaDataNowDescription: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowFadeClassName: {},
    tilesNowNextTileTvMetaDataNowFade: "https://c.animaapp.com/pLg7BaBQ/img/fade-98.svg",
    tilesNowNextTileTvMetaDataNowImg: "https://c.animaapp.com/pLg7BaBQ/img/fade-99.svg",
    tilesNowNextTileTvMetaDataNowFadeClassNameOverride: {},
    tilesNowNextTileTvMetaDataNowDescription1: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowTitle1: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowTitle2: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowProviderLogo1: "https://c.animaapp.com/pLg7BaBQ/img/provider-logo-104@2x.png",
    tilesNowNextTileTvMetaDataNowDescription2: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowImgClassName: {},
    tilesNowNextTileTvMetaDataNowFade1: "https://c.animaapp.com/pLg7BaBQ/img/fade-96.svg",
    tilesNowNextTileTvMetaDataNowFade2: "https://c.animaapp.com/pLg7BaBQ/img/fade-97.svg",
    tilesNowNextTileTvMetaDataNowImgClassNameOverride: {},
    tilesNowNextTileTvMetaDataNowDescription3: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowTitle3: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowTitle4: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowProviderLogo2: "https://c.animaapp.com/pLg7BaBQ/img/provider-logo-104@2x.png",
    tilesNowNextTileTvMetaDataNowDescription4: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowFadeClassName1: {},
    tilesNowNextTileTvMetaDataNowFade3: "https://c.animaapp.com/pLg7BaBQ/img/fade-94.svg",
    tilesNowNextTileTvMetaDataNowFade4: "https://c.animaapp.com/pLg7BaBQ/img/fade-95.svg",
    tilesNowNextTileTvMetaDataNowFadeClassName2: {},
    tilesNowNextTileTvMetaDataNowDescription5: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowTitle5: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowTitle6: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowProviderLogo3: "https://c.animaapp.com/pLg7BaBQ/img/provider-logo-104@2x.png",
    tilesNowNextTileTvMetaDataNowDescription6: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowFadeClassName3: {},
    tilesNowNextTileTvMetaDataNowFade5: "https://c.animaapp.com/pLg7BaBQ/img/fade-92.svg",
    tilesNowNextTileTvMetaDataNowFade6: "https://c.animaapp.com/pLg7BaBQ/img/fade-93.svg",
    tilesNowNextTileTvMetaDataNowFadeClassName4: {},
    tilesNowNextTileTvMetaDataNowDescription7: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowTitle7: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowDescriptionClassName: {},
    tilesNowNextTileTvMetaDataNowTitle8: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
    tilesNowNextTileTvMetaDataNowProviderLogo4: "https://c.animaapp.com/pLg7BaBQ/img/provider-logo-99@2x.png",
    tilesNowNextTileTvMetaDataNowProviderLogoClassName: {},
    tilesNowNextTileTvMetaDataNowDescriptionClassNameOverride: {},
    tilesNowNextTileTvMetaDataNowTitleClassName: {},
    tilesNowNextTileTvMetaDataNowFade7: "https://c.animaapp.com/pLg7BaBQ/img/fade-91.svg",
    tilesNowNextTileTvMetaDataNowFadeClassName5: {},
    tilesNowNextTileTvMetaDataNowFadeClassName6: {},
    tilesNowNextTileTvMetaDataNowDescription8: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowFade8: "https://c.animaapp.com/pLg7BaBQ/img/fade-90.svg",
    tilesNowNextTileTvMetaDataNowTitleClassNameOverride: {},
    tilesNowNextTileTvMetaDataNowDescription9: "https://c.animaapp.com/pLg7BaBQ/img/description-147.svg",
    tilesNowNextTileTvMetaDataNowTitle9: "https://c.animaapp.com/pLg7BaBQ/img/title-102.svg",
  },
};
